Use async with esplora-reqwest
bitcoindevkit/bdk-cli pull request #115
Opened 2022-08-24 22:16 UTC by danielabrozzoni

### Description

### Notes to the reviewers

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk-cli/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [ ] I've added docs for the new feature
* [x] I've updated `CHANGELOG.md`

2022-08-27 15:53 UTC, afilini approved these changes
ACK 2d8b1faadf9627a5aa55407bdd3dd618c0427737

2022-08-29 10:16 UTC, rajarshimaitra commented
I am not sure if this is us or some problem with generic https calls with async-reqwest, but I am getting this error while trying out a wallet sync
```
$ ./target/debug/bdk-cli wallet -d "wpkh(tprv8ZgxMBicQKsPeuazF16EdPZw84eHj55AU8ZKgZgdhu3sXcHnFgjzskfDvZdTaAFHYNCbKqrurFo9onSaT7zGT1i3u3j7LKhVZF5sJA39WPN/86'/1'/0'/0/*)#40hv8z77" sync
[2022-08-29T10:12:21Z ERROR bdk_cli] Esplora(Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("blockstream.info")), port: None, path: "/testnet/api//scripthash/3149608bac07ddc9d628dd85fa0a275d88cc60b4efded5499230973557151e80/txs", query: None, fragment: None }, source: hyper::Error(Connect, "invalid URL, scheme is not http") }))
```

But ureq is working fine on the same esplora endpoint..

2022-08-29 10:23 UTC, rajarshimaitra requested changes

2022-08-29 10:23 UTC, rajarshimaitra commented on Cargo.toml
> +esplora-reqwest = ["esplora", "bdk/use-esplora-reqwest", "async-interface"]
Ah found the problem.. We need to also enable `default-tls` for request.. 
```suggestion
esplora-reqwest = ["esplora", "bdk/use-esplora-reqwest", "bdk/reqwest-default-tls", "async-interface"]
```

2022-08-29 14:38 UTC, notmandatory commented
if we're not going to revert #114 then this PR also needs to be rebased. :-)

2022-08-29 21:07 UTC, danielabrozzoni commented
Rebased :)
@raj I'm ok with your change, but first, could you help me understand why the tests weren't failing? :( With which features did you compile?

2022-08-29 21:22 UTC, notmandatory commented
> @raj I'm ok with your change, but first, could you help me understand why the tests weren't failing? :( With which features did you compile?

This seems to be the issue if you use the `esplora-reqwest` features and try to connect to an https URL (which is default) then we get the below error:
```shell
% RUST_LOG=debug cargo run --features esplora-reqwest -- wallet --descriptor "wpkh(tpubEBr4i6yk5nf5DAaJpsi9N2pPYBeJ7fZ5Z9rmN4977iYLCGco1VyjB9tvvuvYtfZzjD5A8igzgw3HeWeeKFmanHYqksqZXYXGsw5zjnj7KM9/*)" sync
...
ERROR bdk_cli] Esplora(Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("blockstream.info")), port: None, path: "/testnet/api//scripthash/ca0948ef1c5bf5a023f22ed75275d7491c194476c11fbcfc63c0d25ed8234124/txs", query: None, fragment: None }, source: hyper::Error(Connect, "invalid URL, scheme is not http") }))
```

2022-08-30 07:59 UTC, rajarshimaitra commented
> We don't have any CI tests for this sort of thing so only found with the manual testing, not sure it's worth setting up integration tests for this project which is sort of meant to be used for manual testing (and other stuff).

Its definitely worth setting up one, and now that we have automated backend we can use that to cook up a very simple integration test framework using std library only, where we can test out basic operations. This is included in this commit https://github.com/bitcoindevkit/bdk-cli/pull/102/commits/2302ff504bfe5bee72b5da47b5ccab7c5464d537 of #102 . Its still very basic but it works for Rpc and Electrum. Esplora is disabled for now because I was facing some issues with it..

2022-08-30 08:02 UTC, rajarshimaitra commented
> @rajarshimaitra I'm ok with your change, but first, could you help me understand why the tests weren't failing? :( With which features did you compile?

Yes as @notmandatory  noted, we don't have functional tests yet for bdk-cli. We only check for clap structures and some few other functions..

2022-08-30 08:50 UTC, danielabrozzoni commented
Thanks for the explanation, I just updated the PR 🙏🏻

2022-08-30 12:39 UTC, notmandatory approved these changes
ACK 81e72268bc61a078d383b0f8bb1a3b5396313545

2022-08-31 09:44 UTC, rajarshimaitra approved these changes
tACK 81e72268bc61a078d383b0f8bb1a3b5396313545

2022-08-31 16:47 UTC, notmandatory commented
@rajarshimaitra is it ok to merge this before #102? I don't think it will conflict much.

2022-09-02 06:07 UTC, rajarshimaitra commented
> @rajarshimaitra is it ok to merge this before https://github.com/bitcoindevkit/bdk-cli/pull/102? I don't think it will conflict much.

Yes it is.. I will rebase #102 once this is in..

2022-09-02 14:12 UTC, afilini commented on Cargo.toml
> +tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
This should be optional and only included with `async-interface`

2022-09-02 14:30 UTC, afilini reviewed
ACK 3ad5b02d7f49b7249cf183c1db84400001bf131a

2022-09-02 14:50 UTC, afilini reviewed
reACK 8d876ef376097e6361d9f8495afb82a3ef03b87b

2022-09-02 14:50 UTC, merged