README.md:better markdown syntax for lists
bitcoindevkit/bdk-cli pull request #165
Opened 2023-11-22 18:11 UTC by RandyMcMillan

2023-11-22 18:13 UTC, RandyMcMillan commented
This doesnt effect how README.md is rendered on GitHub.com.
It enables correct list rendering in other markdown clients.

2023-11-22 18:17 UTC, RandyMcMillan commented
Before:

![pr-165-before](https://github.com/bitcoindevkit/bdk-cli/assets/152159/4a79f141-ae4c-4481-a12a-370942d873ec)

After:

![pr-165-after](https://github.com/bitcoindevkit/bdk-cli/assets/152159/3a82813a-2a96-42d5-81f1-e18313d78cb1)

2023-11-23 14:48 UTC, thunderbiscuit commented
Good catch. When looking at it though I see a few more things that could be improved. Do you mind fixing these as well?

- The first 3 bullets under "This crate can be used for the..." can all be at the same level (the last 2 are not subpoints of the first one).
- The other list (Database Options, Blockchain Options, etc.)  do not need indentation at the first level, and the second level can get 4 spaces of indentation.

Roughly I'd like us to try to adhere to the [Google Markdown Styleguide](https://google.github.io/styleguide/docguide/style.html), so that markdown is rendered the same everywhere. Thanks for catching this!

2023-11-23 14:49 UTC, thunderbiscuit requested changes
Good catch. When looking at it though I see a few more things that could be improved. Do you mind fixing these as well?

- The first 3 bullets under "This crate can be used for the..." can all be at the same level (the last 2 are not subpoints of the first one).
- The other list (Database Options, Blockchain Options, etc.)  do not need indentation at the first level, and the second level can get 4 spaces of indentation.

Roughly I'd like us to try to adhere to the [Google Markdown Styleguide](https://google.github.io/styleguide/docguide/style.html), so that markdown is rendered the same everywhere. Thanks for catching this!

2023-11-28 23:10 UTC, RandyMcMillan commented
6d84b96: update per suggestions

2024-01-12 19:29 UTC, thunderbiscuit commented
@RandyMcMillan if you can give me commit access to your PR I'll be able to push some small fixes and get this merged. I'm trying to clean up some of the PRs and move stuff along, sorry it's slow going.

2024-01-14 15:35 UTC, RandyMcMillan commented
![Screen Shot 2024-01-14 at 10 34 38 AM](https://github.com/bitcoindevkit/bdk-cli/assets/152159/4f28c9d2-bfb4-41ca-8fe6-8a1d2ec2cc60)

2024-01-14 16:10 UTC, thunderbiscuit commented
Actually this will (I think) work, but in general you don't need to grant complete access to your repo for maintainers to be able to push commits on a PR. 

I think this is the article to take a look at: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2024-01-14 16:23 UTC, thunderbiscuit commented
@notmandatory I don't have permissions to merge this because of the protections on the `master` branch. The PR currently fails the CI but this is a docs PR and I don't want to get into fixing all the pins on the dependencies here.

2024-01-14 17:20 UTC, notmandatory commented
I think we need to do a couple things before we can merge this PR:
1. publish release bdk 0.29.1 which has MSRV fixes or just bump MSRV to 1.63 and fix CI in a 0.30.0 version
2. update bdk-cli to use bdk 0.29.1 and fix any other msrv issues

2025-05-25 12:23 UTC, closed without merging