Fix bumpfee after bdk v0.10.0 update
bitcoindevkit/bdk-cli pull request #42
Opened 2021-09-19 06:01 UTC by rajarshimaitra

### Description

This builds on top of #36, so should be merged after it.

This fixes the issue I pointed at https://github.com/bitcoindevkit/bdk/issues/427. I found way around to get the `script_pubkey` for and output without a need of `get_tx()` function. 

Added one extra argument to `bump_fee` to select the utxo whose output is to be reduced.

### Notes to the reviewers

Please check the `bump_fee` function manually. I have checked them locally and it works. But there is no unit tests for these. 

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk-cli/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

2021-10-05 13:35 UTC, rajarshimaitra commented
Rebased on master

2021-10-05 19:19 UTC, notmandatory requested changes
LGTM but I still need to manually test. Found a small typo that should be fixed.

2021-10-05 19:19 UTC, notmandatory commented on src/lib.rs
> +            let script_pubey = match wallet.get_utxo(outpoint) {
small typo:
```suggestion
            let script_pubkey = match wallet.get_utxo(outpoint) {
```

2021-10-05 19:19 UTC, notmandatory commented on src/lib.rs
> +                tx_builder.allow_shrinking(script_pubey)?;
```suggestion
                tx_builder.allow_shrinking(script_pubkey)?;
```

2021-10-06 11:30 UTC, rajarshimaitra commented
Thanks. Updated..

2021-10-08 00:05 UTC, notmandatory commented
I think I have a better approach in #45, please take a look and let me know what you think.

2021-11-01 09:54 UTC, rajarshimaitra commented
Closed in favor of #45

2021-11-01 09:54 UTC, rajarshimaitra commented
Close in favor of #45

2021-11-01 09:54 UTC, closed without merging