if no wallet name was provided, use one derived from the descriptor
bitcoindevkit/bdk-cli pull request #57
Opened 2021-11-25 16:50 UTC by ulrichard

### Description

if no wallet name was provided, use one derived from the descriptor

### Notes to the reviewers

Is there a better place to use wallet_name_from_descriptor so that the generated name shows up in the unit tests instead of the placeholder?

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk-cli/blob/master/CONTRIBUTING.md)
* [ ] I ran `cargo fmt` and `cargo clippy` before committing

2021-11-28 03:59 UTC, notmandatory commented
How about making `WalletOpts.wallet` an `Option<String>` ? Then you could avoid the "main_marker_will_be_replaced" default value and only do the replacement when `WalletOpts.wallet` is `None`.

2021-11-30 07:22 UTC, ulrichard commented
@notmandatory  Yes, of course. Sometimes the solution is so obvious that I have no clue why I didn't find it myself. Thanks.

2021-12-13 15:02 UTC, rajarshimaitra requested changes
tACK https://github.com/bitcoindevkit/bdk-cli/pull/57/commits/773f2dbeb9e272d9cf6ad54d1f8231816a247dd7. Code changes looks good to me.

Below are some minor nits.

I think this warrant an addition in changelog. This is probably a breaking change and we should document this.

2021-12-15 06:36 UTC, ulrichard commented on src/bdk_cli.rs
> +    let wallet_name = wallet_opts.wallet.as_ref().unwrap_or(&default_wallet_name);
The suggested code leads to: 
> expected `&std::string::String`, found struct `std::string::String`
> help: consider borrowing here: `&"default".to_string()`
And this suggestion leads to:
> creates a temporary which is freed while still in use
That's why I made a separate variable.
But as_deref() did the trick.

2021-12-15 06:39 UTC, ulrichard commented on src/lib.rs
> +///               #[cfg(any(feature = "esplora-ureq", feature = "esplora-reqwest"))]
Ah yes. I thought about this, was not sure and wanted to try it. But then forgot about it.

2022-01-06 04:40 UTC, rajarshimaitra requested changes
tACK https://github.com/bitcoindevkit/bdk-cli/pull/57/commits/adfdd8c49bdd0683690f55c43abe2ca3c25b5161

Verified that each new descriptor is creating its own wallet directory. Updated checksum mismatch error message is being displayed for wallet with same name but different descriptor.

Just one single nit.

2022-01-11 13:50 UTC, rajarshimaitra approved these changes
ReACK https://github.com/bitcoindevkit/bdk-cli/pull/57/commits/e52e81951e229fd79225349951699a034874b65d

Tested it locally. All seem to be working fine.

There are rooms for few improvement but that can be done in a future PR.

This LGTM.

@notmandatory will wait for you take a look before merging.

2022-01-17 19:00 UTC, notmandatory approved these changes
tACK e52e81951e229fd79225349951699a034874b65d

Works as expected. One suggestion for future PRs is to separate unrelated changes in to different PRs or at least separate commits. In this case the `bdk` version upgrade changes were mixed with the wallet name generation changes which made it a little harder to review. But anyway a good usability improvement!

2022-01-25 19:40 UTC, merged